on: [push]

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cypress run
              uses: cypress-io/github-action@v3
              with:
                  project: ./site
                  browser: chrome
                  build: yarn build
                  start: yarn start
                  wait-on: "http://localhost:3000"
              env:
                  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
                  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
