name: Jest Testing

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:

basic-without-binary-install:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Cypress tests
          uses: ./
          with:
              working-directory: examples/basic
              # since we do not install Cypress
              # we should not attempt to run tests
              runTests: false
          env:
              # skip the binary install
              CYPRESS_INSTALL_BINARY: 0

    build:
        runs-on: ubuntu-latest
        env:
            NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

        strategy:
            matrix:
                node-version: [16.x, 18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
